# Generated by Django 4.2.8 on 2023-12-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="text",
            field=models.TextField(default="kjhkjj", verbose_name="Текст"),
            preserve_default=False,
        ),
    ]
