# Generated by Django 4.2.8 on 2023-12-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_answer_text"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="message_que_date_68ebb4_idx",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="date",
            new_name="date_answer",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="text",
            new_name="text_answer",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="date",
            new_name="date_question",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="text_question",
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["date_answer"], name="message_ans_date_an_f087f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["date_question"], name="message_que_date_qu_55a7e3_idx"
            ),
        ),
    ]
