# Generated by Django 4.2.8 on 2024-01-16 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_archive_date_alter_task_finish_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0003_remove_question_message_que_date_68ebb4_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_body", models.TextField(verbose_name="Текст сообщения")),
                (
                    "message_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=8, verbose_name="Статус сообщения"),
                ),
            ],
            options={
                "verbose_name": "Статус сообщения",
                "verbose_name_plural": "Статусы сообщений",
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_body", models.TextField(verbose_name="Текст")),
                (
                    "reply_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор ответа",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply",
                        to="message.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="question",
            name="task",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.AddField(
            model_name="message",
            name="message_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message",
                to="message.messagestatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["reply_date"], name="message_rep_reply_d_b8f97c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_date"], name="message_mes_message_b45720_idx"
            ),
        ),
    ]
