[tool.ruff]
line-length = 80
select = ["E", "F", "I"]
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".env",
    "venv",
    "env",
    "migrations",
    "infra",
    "docs",
    ".vscode",
]

[tool.ruff.per-file-ignores]
"*/settings.py" = ["E501"]

[tool.ruff.isort]
combine-as-imports = true
known-local-folder = []  # Здесь указывать название локального модуля, для корректной сортировки импортов ["my_module"]
