# Generated by Django 4.2.8 on 2024-01-17 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(help_text='The creator of the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='task',
            name='performers',
            field=models.ManyToManyField(help_text='The performers of the task', related_name='performers', to=settings.AUTH_USER_MODEL, verbose_name='performers'),
        ),
    ]
