# Generated by Django 4.2.8 on 2024-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, help_text='The link of the task', max_length=2048, verbose_name='link'),
        ),
    ]
