# Generated by Django 4.2.8 on 2024-02-12 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(help_text='The creator of the task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(help_text='The performer of the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for_user', to=settings.AUTH_USER_MODEL, verbose_name='performer'),
        ),
    ]
