# Generated by Django 4.2.8 on 2023-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='archive_date',
            field=models.DateField(help_text='The archive date of the task', null=True, verbose_name='archive date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(help_text='The finish date of the task', null=True, verbose_name='finish date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='inprogress_date',
            field=models.DateField(help_text='The "in progress" date of the task', null=True, verbose_name='"in progress" date'),
        ),
    ]
