# Generated by Django 4.2.8 on 2024-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='archive_date',
            field=models.DateTimeField(blank=True, help_text='The archive date of the task', null=True, verbose_name='archive date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The create date of the task', verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(help_text='The deadline date of the task', verbose_name='deadline date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(blank=True, help_text='The done date of the task', null=True, verbose_name='done date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='inprogress_date',
            field=models.DateTimeField(blank=True, help_text='The "in progress" date of the task', null=True, verbose_name='"in progress" date'),
        ),
    ]
