# Generated by Django 4.2.8 on 2024-01-18 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(help_text='The creator of the task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='performers',
            field=models.ManyToManyField(help_text='The performers of the task', related_name='tasks_for_user', to=settings.AUTH_USER_MODEL, verbose_name='performers'),
        ),
    ]
