version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: zali1813/short_tracker_frontend:v1
    # restart: always
    volumes:
      - ../frontend/:/app/result_build/
    # depends_on:
    #  - db

  backend:
    container_name: backend
    image: zali1813/short_tracker_backend:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    # depends_on:
    #  - frontend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    # depends_on:
    #  - backend
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  bot:
    container_name: bot
    image: zali1813/short_tracker_bot:v1
#    build:
#      context: ../short_tracker_bot
#      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  static_value:
  media_value:
  postgres_data:
  redis_data:
  
