# Generated by Django 4.2.8 on 2024-02-12 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telegram_nickname",
            field=models.CharField(
                max_length=33,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="nickname содержит недопустимый символ",
                        regex="^@[a-zA-Z0-9_]{5,33}\\Z",
                    )
                ],
                verbose_name="Никнейм Телеграм",
            ),
        ),
    ]
