# Generated by Django 4.2.8 on 2023-12-28 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='email содержит недопустимый символ', regex='^((?!\\.)[\\w\\-_.]*[^.])(@\\w+)(\\.\\w+(\\.\\w+)?[^.\\W])$')], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_nickname',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='nickname содержит недопустимый символ', regex='^@[a-zA-Z0-9_]{5,32}\\Z')], verbose_name='Никнейм Телеграм'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='никнейм'),
        ),
    ]
