# Generated by Django 4.2.8 on 2024-02-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allownotification",
            name="notification",
            field=models.CharField(
                choices=[
                    ("deadline", "Дедлайн"),
                    ("msg", "Сообщения"),
                    ("status", "Статусы"),
                    ("tasks", "Задачи"),
                ],
                max_length=10,
                verbose_name="Уведомление",
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
