# Generated by Django 4.2.8 on 2024-02-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_allownotification_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allownotification',
            name='allow_notification',
            field=models.BooleanField(default=True, verbose_name='Разрешить уведомления'),
        ),
        migrations.AlterField(
            model_name='allownotification',
            name='notification',
            field=models.CharField(choices=[('tasks', 'Задачи'), ('msg', 'Сообщения'), ('status', 'Статусы'), ('deadline', 'Дедлайн')], max_length=10, verbose_name='Уведомление'),
        ),
        migrations.AddConstraint(
            model_name='allownotification',
            constraint=models.UniqueConstraint(fields=('user', 'notification'), name='unique_notification_for_user'),
        ),
    ]
