# Generated by Django 4.2.8 on 2024-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_allownotification_allow_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allownotification',
            name='notification',
            field=models.CharField(choices=[('deadline', 'Дедлайн'), ('tasks', 'Задачи'), ('status', 'Статусы'), ('msg', 'Сообщения')], max_length=10, verbose_name='Уведомление'),
        ),
    ]
