# Generated by Django 4.2.8 on 2024-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_allownotification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allownotification',
            name='notification',
            field=models.CharField(choices=[('deadline', 'Дедлайн'), ('status', 'Статусы'), ('msg', 'Сообщения'), ('tasks', 'Задачи')], max_length=10, verbose_name='Уведомление'),
        ),
    ]
